version: '2'
services:
  backend:
    build:
      context: ./app/
      dockerfile: Dockerfile
    image: i-srv-shipping
    container_name: c-srv-shipping
    ports:
      - "8080:8080"
    volumes:
      - ./app:/var/www
    networks:
      - net
networks:
  net:
    driver: bridge